CREATE DATABASE IF NOT EXISTS movie_sqlbolt;
USE movie_sqlbolt;
CREATE TABLE IF NOT EXISTS movies(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(40) NOT NULL,
    director VARCHAR(30) NOT NULL,
    year SMALLINT UNSIGNED NOT NULL,
    length_minutes SMALLINT UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS boxoffice(
	movie_id INT UNSIGNED NOT NULL PRIMARY KEY,
    rating FLOAT NOT NULL,
    domestic_sales INT UNSIGNED NOT NULL,
    international_sales INT UNSIGNED NOT NULL
);